name: Build
on: [push]

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: android-actions/setup-android@v2
      - run: cd android
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v2
        with:
          name: Android
          path: app/build/outputs/apk/debug/app-debug.apk